// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGLWEfej3LxAn4WWxFEhd7QO9ep6uHtr4',
    appId: '1:258237932870:web:0d66ed21742811faf9f147',
    messagingSenderId: '258237932870',
    projectId: 'college-hearts-demo',
    authDomain: 'college-hearts-demo.firebaseapp.com',
    storageBucket: 'college-hearts-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2QOcaCGYDITkRgmqqCc6DN7na9ItrpM',
    appId: '1:258237932870:android:2b4dcb337b5e3136f9f147',
    messagingSenderId: '258237932870',
    projectId: 'college-hearts-demo',
    storageBucket: 'college-hearts-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOYDGH_4NzytaXgEbxtzKihYawPG-3sE',
    appId: '1:258237932870:ios:e1742336d16c38c7f9f147',
    messagingSenderId: '258237932870',
    projectId: 'college-hearts-demo',
    storageBucket: 'college-hearts-demo.appspot.com',
    iosClientId: '258237932870-lrlufu15ql3shb1ct2gd14im7umemh6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnOYDGH_4NzytaXgEbxtzKihYawPG-3sE',
    appId: '1:258237932870:ios:e1742336d16c38c7f9f147',
    messagingSenderId: '258237932870',
    projectId: 'college-hearts-demo',
    storageBucket: 'college-hearts-demo.appspot.com',
    iosClientId: '258237932870-lrlufu15ql3shb1ct2gd14im7umemh6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeTinder',
  );
}
